services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - kavita_config:/config
      - ebooks_library:/data
    ports:
      - 5000:5000
    restart: unless-stopped

volumes:
  kavita_config:
  ebooks_library:
    external: True
