services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    restart: always
    read_only: true
    user: "1000:1000"
    ports:
      - "8888:8080"
    volumes:
      - data:/srv/data

volumes:
  data:
