services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  n8n_files:
  n8n_postgres_data:
