services:
  hawser:
    image: ghcr.io/finsys/hawser:latest
    container_name: hawser
    restart: unless-stopped
    ports:
      - "2376:2376"
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
    environment:
      - TOKEN=qcNwUqbgPSQTiQquD8waMj5
