services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - calibre_web_config:/config
      - ebooks_library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

volumes:
  calibre_web_config:
  ebooks_library:
    external: True
