services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://192.168.12.151:8091
      TOKEN: EvrIZdupNHXJyEFdMpAa
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHK3ckn/gTe88kj1KLkRyYr4rX765k0d8nFDrVvJnXUF"

volumes:
  beszel_agent_data:
  beszel_socket:
    external: True
    name: beszel_beszel_socket
