name: time-machine
services:
    timemachine:
        restart: always
        container_name: timemachine
        network_mode: host
        environment:
            - TM_USERNAME=timemachine
            - TM_GROUPNAME=timemachine
            - PASSWORD=timemachine
            - TM_UID=1000
            - TM_GID=1000
            - SET_PERMISSIONS=false
            - VOLUME_SIZE_LIMIT=0
        volumes:
            - time_machine_data:/opt/timemachine
        tmpfs: /run/samba
        image: mbentley/timemachine:smb
volumes:
    time_machine_data:
        external: true
