services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8000:8000"     # Optional für Edge-Agent
      - "9443:9443"     # HTTPS-Zugriff auf Portainer (Web-UI)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    external: true
