services:
    open-webui:
        volumes:
            - open-webui:/app/backend/data
        environment:
            - OLLAMA_BASE_URL=http://192.168.12.151:11434
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main

    ollama:
        restart: always
        devices:
            - /dev/kfd
            - /dev/dri
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        environment:
            - HSA_OVERRIDE_GFX_VERSION=10.3.0
            - HCC_AMDGPU_TARGET=gfx1030
        image: ollama/ollama:rocm
volumes:
    ollama:
    open-webui:
