services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8091:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket

volumes:
  beszel_data:
  beszel_socket:
